#---------------------------------------------------#
## æ›´æ–°ï¼š2020-05-04
## é“¾æ¥ï¼šhttps://lolico.me/subscribe/Clash/config.yaml
#---------------------------------------------------#

port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5

Proxy:
  - {name: "ğŸµ è§£é”èŠ‚ç‚¹1", server: music.desperadoj.com, port: 30001, type: ss, cipher: aes-128-gcm, password: desperadoj.com_free_proxy_gt5i}
  - {name: "ğŸµ è§£é”èŠ‚ç‚¹2", server: 106.52.127.72, port: 19951, type: http}
  - {name: "ğŸµ è§£é”èŠ‚ç‚¹3", server: taron.top, port: 100, type: http}
  - {name: "ğŸµ è§£é”èŠ‚ç‚¹4", server: music.griouges.cn, port: 39000, type: http}

Proxy Group:
  - name: ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹
    type: select
    proxies:
      - ğŸµ è§£é”èŠ‚ç‚¹1
      - ğŸµ è§£é”èŠ‚ç‚¹2
      - ğŸµ è§£é”èŠ‚ç‚¹3
      - ğŸµ è§£é”èŠ‚ç‚¹4
      - DIRECT

Rule:
  # Netease Music
  - DOMAIN,music.163.com,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹
  - DOMAIN,api.iplay.163.com,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹
  - DOMAIN,apm.music.163.com,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹
  - DOMAIN,apm3.music.163.com,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹
  - DOMAIN,interface.music.163.com,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹
  - DOMAIN,interface3.music.163.com,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹
  - IP-CIDR,39.105.63.80/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,45.254.48.1/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,47.100.127.239/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,59.111.160.195/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,59.111.160.197/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,59.111.181.35/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,59.111.181.38/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,59.111.181.60/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,101.71.154.241/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,103.126.92.132/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,103.126.92.133/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,112.13.119.17/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,112.13.122.1/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,115.236.118.33/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,115.236.121.1/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,118.24.63.156/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,193.112.159.225/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,223.252.199.66/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve
  - IP-CIDR,223.252.199.67/32,ğŸ¸ç½‘æ˜“äº‘éŸ³ä¹,no-resolve

  # Netease Music Advertising
  - DOMAIN,admusicpic.music.126.net,REJECT
  - DOMAIN,iadmat.nosdn.127.net,REJECT
  - DOMAIN,iadmusicmat.music.126.net,REJECT
  - DOMAIN,iadmusicmatvideo.music.126.net,REJECT

  # Final
  - MATCH,DIRECT